// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnqwtegdwnzcgexudvyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImducXd0ZWdkd256Y2dleHVkdnl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYzNzExMTMsImV4cCI6MjA5MTk0NzExM30.BlmlN8kRStHiQ7rVi0pb9eYF2HQCFvi9joZbj1ALPYc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});